name: 🟢 GreenLight Issue
description: Report an issue with production-ready code or request a feature that's ready to implement
title: "[GreenLight] "
labels: ["greenlight", "ready"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🟢 GreenLight Issue
        This template is for production-ready issues - all checks pass, ready to go!
        
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue or feature request
      placeholder: What needs to be done?
    validations:
      required: true
      
  - type: textarea
    id: context
    attributes:
      label: Context & Background
      description: Provide context about why this is needed
      placeholder: Why is this important?
    validations:
      required: true
      
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What defines "done" for this issue?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What's the priority level?
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or relevant information
      placeholder: Any additional details?
    validations:
      required: false
      
  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Confirm the following before submitting
      options:
        - label: I have searched for similar issues
          required: true
        - label: This issue is ready for implementation
          required: true
        - label: I have provided clear acceptance criteria
          required: true
        - label: This follows BlackRoad Codex standards
          required: true
