name: 🟡 YellowLight Issue
description: Report an issue that needs discussion or has some uncertainties
title: "[YellowLight] "
labels: ["yellowlight", "needs-discussion"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🟡 YellowLight Issue
        This template is for issues that need discussion, have warnings, or require clarification.
        
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue or idea
      placeholder: What's the situation?
    validations:
      required: true
      
  - type: textarea
    id: concerns
    attributes:
      label: Concerns & Uncertainties
      description: What are the warnings or concerns?
      placeholder: What needs to be discussed or clarified?
    validations:
      required: true
      
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: What do you think might work?
      placeholder: Potential approaches or solutions?
    validations:
      required: false
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Approaches
      description: What other options have you considered?
      placeholder: Other ways to handle this?
    validations:
      required: false
      
  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      description: What kind of issue is this?
      options:
        - Technical Debt
        - Improvement
        - Discussion
        - Question
        - Deprecation Warning
    validations:
      required: true
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or information
      placeholder: Any other relevant details?
    validations:
      required: false
      
  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Confirm the following before submitting
      options:
        - label: I have searched for similar issues
          required: true
        - label: This issue requires discussion before implementation
          required: true
        - label: I have outlined the concerns clearly
          required: true
